name: Node.js CI

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          set +eo pipefail
          npx jest --json > results.json
          results=$(<results.json)
          echo 'RESULTS<<EOF' >> $GITHUB_ENV
          echo "$results" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Post Results
        uses: indiesdev/curl@v1
        with:
          url: ${{ secrets.RESULTSENDPOINT }}
          method: "POST"
          accept: 200,201,204
          headers: '{ "Content-Type": "text/plain", "Lang": "javascript", "Author": "${{ github.actor }}", "Repository": "${{ github.repository }}", "Branch": "${{ github.ref_name }}" }'
          body: "${{ env.RESULTS }}"
          timeout: 10000
          is_debug: true
